Lists Week 7 Milestone
ucsd-cse231-s22/chocopy-wasm-compiler-B pull request #29
Opened 2022-05-14 01:53 UTC by lim-rachel

2022-05-18 20:04 UTC, yalhessi requested changes
Great work!

I really enjoyed going through the progress you've been making. Lots of great work here!

I encourage you to consider different designs for checking the validity of an index. We would certainly be very hesitant to approve anything that changes IR (or to a lesser degree compiler). If you consider what you're trying to do here, you're translating an index access to an index check, and then performing the access. This can easily be done in `lower` where you append a call to the statements being generated for both `index` and `index-assign`. To be more clear, you can replace line 297 for example with a `{tag: "call"}` where you call a function that does the checks. This will require you to pull the logic you embedded in `compiler` into a seperate wasm function, and make sure that wasm function is visible to our program. I think that would be the cleanest way to go about what you're trying to do.

2022-05-18 20:04 UTC, yalhessi commented on compiler.ts
> +          (else)
You can just delete this else since it's doing nothing.

2022-05-18 20:04 UTC, yalhessi commented on ir.ts
> +  | {  a?: A, tag: "check-index", address: Value<A>, index: Value<A> }
Adding to IR should be avoided at all costs if possible. The point is to keep IR minimal.

2022-05-19 01:20 UTC, xChickens commented on compiler.ts
> +          (else)
Done.

2022-05-19 02:53 UTC, xChickens commented on ir.ts
> +  | {  a?: A, tag: "check-index", address: Value<A>, index: Value<A> }
Removed in latest commit.

2022-05-19 02:56 UTC, xChickens approved these changes

2022-05-19 02:56 UTC, xChickens approved these changes

2022-05-24 18:51 UTC, merged